const POLICY = {
  CAPolicy: [{
    ID: 11,
    Name: "Out of Band",
    Active: true,
    AllowUserMode: false,
    SNChangesEnable: true,
    NamePolicy: [{
      IsRequired: false,
      Order: 2,
      OID: "1.2.840.113549.1.9.1",
      Name: "E-Mail",
      Value: null,
      StringIdentifier: "E",
    }, {
      IsRequired: false,
      Order: 8,
      OID: "1.2.643.3.131.1.1",
      Name: "ИНН",
      Value: null,
      StringIdentifier: "INN",
    }, {
      IsRequired: false,
      Order: 4,
      OID: "2.5.4.7",
      Name: "Населенный пункт",
      Value: null,
      StringIdentifier: "L",
    }, {
      IsRequired: false,
      Order: 7,
      OID: "1.2.643.100.1",
      Name: "ОГРН",
      Value: null,
      StringIdentifier: "OGRN",
    }, {
      IsRequired: false,
      Order: 5,
      OID: "2.5.4.10",
      Name: "Организация",
      Value: null,
      StringIdentifier: "O",
    }, {
      IsRequired: false,
      Order: 6,
      OID: "2.5.4.11",
      Name: "Подразделение",
      Value: null,
      StringIdentifier: "OU",
    }, {
      IsRequired: false,
      Order: 3,
      OID: "2.5.4.8",
      Name: "Регион",
      Value: null,
      StringIdentifier: "S",
    }, {
      IsRequired: false,
      Order: 9,
      OID: "2.5.4.6",
      Name: "Страна",
      Value: null,
      StringIdentifier: "C",
    }, {
      IsRequired: true,
      Order: 1,
      OID: "2.5.4.3",
      Name: "Общее имя",
      Value: null,
      StringIdentifier: "CN",
    },
    ],
    EKUTemplates: {
      "Временный сертификат администратора УЦ": ["1.2.643.2.2.34.2", "1.2.643.2.2.34.4", "1.3.6.1.5.5.7.3.2"],
      "Временный сертификат оператора УЦ": ["1.2.643.2.2.34.2", "1.2.643.2.2.34.5", "1.3.6.1.5.5.7.3.2"],
      "Временный сертификат пользователя УЦ": ["1.2.643.2.2.34.2 ", "1.3.6.1.5.5.7.3.2"],
      "Временный сертификат пользователя УЦ1": ["1.2.643.2.2.34.6", "1.3.6.1.5.5.7.3.2"],
      "Сертификат пользователя УЦ": ["1.2.643.2.2.34.6", "1.3.6.1.5.5.7.3.2"],
    },
    CAType: "DSSOutOfBandEnroll",
    ValidationMode: "CertificateAuthority",
  },
  ],
  CSPsPolicy: [{
    ID: "67e6f39d-c6c5-4ce6-9535-4e22bae84786",
    GroupID: "e8e67f9e-7eed-4116-ad98-20582e4d766e",
    TypeID: 2,
    ProviderName: "Crypto-Pro GOST R 34.10-2001 Cryptographic Service Provider",
    ProviderType: 75,
    KeyLength: 512,
    HashAlgorithms: ["GOST R 34.11-94"],
    Description: "GOST 2001",
  }, {
    ID: "60e9912c-68a8-4608-b1c2-0c6a074456e8",
    GroupID: "648092d3-46a9-422a-9240-d32c58cc498b",
    TypeID: 2,
    ProviderName: "Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider",
    ProviderType: 80,
    KeyLength: 512,
    HashAlgorithms: ["GR 34.11-2012 256"],
    Description: "GOST 2012",
  },
  ],
  ActionPolicy: [{
    DisplayName: "Выпуск маркера (вход в ЦИ)",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/issue",
    Action: "Issue",
    MfaRequired: false,
  }, {
    DisplayName: "Подпись документа",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/signdocument",
    Action: "SignDocument",
    MfaRequired: false,
  }, {
    DisplayName: "Подпись пакета документов",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/signdocuments",
    Action: "SignDocuments",
    MfaRequired: false,
  }, {
    DisplayName: "Расшифрование документа",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/decryptdocument",
    Action: "DecryptDocument",
    MfaRequired: false,
  }, {
    DisplayName: "Создание запроса на сертификат",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/createrequest",
    Action: "CreateRequest",
    MfaRequired: false,
  }, {
    DisplayName: "Смена пин-кода закрытого ключа",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/changepin",
    Action: "ChangePin",
    MfaRequired: false,
  }, {
    DisplayName: "Обновление сертификата",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/renewcertificate",
    Action: "RenewCertificate",
    MfaRequired: false,
  }, {
    DisplayName: "Отзыв сертификата",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/revokecertificate",
    Action: "RevokeCertificate",
    MfaRequired: false,
  }, {
    DisplayName: "Приостановление действия сертификата",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/holdcertificate",
    Action: "HoldCertificate",
    MfaRequired: false,
  }, {
    DisplayName: "Возобновление действия сертификата",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/unholdcertificate",
    Action: "UnholdCertificate",
    MfaRequired: false,
  }, {
    DisplayName: "Удаление сертификата",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/deletecertificate",
    Action: "DeleteCertificate",
    MfaRequired: false,
  }, {
    DisplayName: "Доступ к закрытому ключу",
    Uri: "http://dss.cryptopro.ru/identity/claims/action/privatekeyaccess",
    Action: "PrivateKeyAccess",
    MfaRequired: false,
  },
  ],
  PinCodeMode: "Allow",
  TspServices: [{
    Name: "TestTSP",
    Title: "TestTSP",
    Url: "http://TEST-DSS-W8R2/TSP/tsp.srf",
  },
  ],
  TransactionConfirmation: "NotSet",
  AllowedSignatureTypes: ["GOST3410", "CMS", "CAdES", "XMLDSig", "MSOffice", "PDF"],
};

export default POLICY;
export const UID = "051fbf41-3bc5-8c69-9f59-a80e11a5157b";
export const NORMALIZE_POLICY = POLICY.ActionPolicy.filter(function(item: any) {
  return item.Action === "Issue" || item.Action === "SignDocument" || item.Action === "SignDocuments";
});
